services:
  postgres:
    image: postgres:17.5-alpine
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGERS_USER=user
      - POSTGRES_DB=todos


